<?php

namespace App\Exports;

use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\FromArray;

class EmployeesExport implements FromArray
{
    public function array(): array
    {
        $employees = DB::table('employee_general_data')->where('statue' , 'active')->get()->toArray();
        $employee_array[] = [
            'الكود',
            'الاسم بالعربي',
            'الاسم انجليزي',
            'اسم الشهره',
            'الصوره ',
            'الجنس',
            'الهاتف',
            'الهاتف البديل',
            'العنوان',
            'البريد الالكتروني',
            'الجنسية',
            'الديانه',
            'محل الميلاد',
            'تاريخ الميلاد',
            'رقم الهوية',
            'تاريخ انتهاء الهوية',
            'رقم الاقامة',
            'تاريخ اصدار الأقامه',
            'تاريخ انتهاء الاقامة',
            'الوظيفه في الأقامه',
            'رقم الجواز',
            'تاريخ اصدار الجواز',
            'تاريخ انتهاء الجواز',
            'رقم رخصه القياده',
            'تاريخ انتهاء رخصه القياده',
            'رقم الشهاده الصحيه',
            'تاريخ انتهاءالشهاده الصحيه',
            'تاريخ الغاء الشهاده الصحيه',
            'المؤهل',
            'الجامعه',
            'سنه التخرج',
            'الخبرات السابقه',
            'كود الكفيل',
            'الكفيل',
            'نوع العقد',
            'تاريخ التعيين',
            'تاريخ  بدايه آخر عقد',
            'تاريخ نهايه آخر عقد',
            'تاريخ الالتحاق بالتأمين',
            'المرتب الأساسي',
            'المرتب المتغير',
            'الوظيفة',
            'القسم',
            'الاداره',
            'الفرع',
            'كود المدير المباشر',
            'اسم المدير المباشر',
            'يعامل ضمن الحضور والأنصراف؟',
            'له اجازات سنويه؟',
            'عدد الأيام خلال السنه',
            'له مكافئه نهايه خدمه؟',
            'عدد الأيام للسنه',
            'خاضع للتامين الصحي ؟',
            'نوع التأمين',
            'اسم شركه التأمين',
            'رقم بوليصه التأمين',
            'تاريخ بدايه التأمين',
            'تاريخ نهايه التأمين',
            'رقم الحساب البنكي',
            'اسم صاحب الحساب البنكي',
            'البنك التابع له',
            'كود البنك',
        ];
        foreach($employees as $employee)
        {
            $employee_array[] = [
                'الكود'=>$employee->code,
                'الاسم بالعربي'=> $employee->employee_name,
                'الاسم انجليزي'=> $employee->employee_name_en,
                'اسم الشهره'=> $employee->employee_short_name,
                'الصوره '=> $employee->employee_img,
                'الجنس'=> $employee->gender,
                'الهاتف'=>$employee->phone_1,
                'الهاتف البديل'=>$employee->phone_2,
                'العنوان'=>$employee->address,
                'البريد الالكتروني'=>$employee->email,
                'الجنسية'=> DB::table('countries')->where('id',$employee->country_id)->value('name'),
                'الديانه'=>$employee->religion,
                'محل الميلاد'=>$employee->birth_place,
                'تاريخ الميلاد'=> $employee->birth_date,
                'رقم الهوية'=>$employee->national_id_number,
                'تاريخ انتهاء الهوية'=>$employee->national_id_expiry_date,
                'رقم الاقامة'=>$employee->residency_number,
                'تاريخ اصدار الأقامه'=>$employee->residency_start_date,
                'تاريخ انتهاء الاقامة'=>$employee->residency_expiry_date,
                'الوظيفه في الأقامه'=>$employee->residency_job,
                'رقم الجواز'=>$employee->passport_number,
                'تاريخ اصدار الجواز'=>$employee->passport_start_date,
                'تاريخ انتهاء الجواز'=>$employee->passport_expiry_date,
                'رقم رخصه القياده'=>$employee->driving_licence_number,
                'تاريخ انتهاء رخصه القياده'=>$employee->driving_licence_expiry_date,
                'رقم الشهاده الصحيه'=>$employee->healthy_certificate,
                'تاريخ انتهاءالشهاده الصحيه'=>$employee->healthy_certificate_expiry_date,
                'تاريخ الغاء الشهاده الصحيه'=>$employee->healthy_certificate_cancel_date,
                'المؤهل'=>$employee->educational_qualification,
                'الجامعه'=>$employee->educational_university,
                'سنه التخرج'=>$employee->educational_qualification_year,
                'الخبرات السابقه'=>$employee->experience,
                'كود الكفيل'=>DB::table('guarantors')->where('id',$employee->guarantor_id)->value('code'),
                'الكفيل'=>DB::table('guarantors')->where('id',$employee->guarantor_id)->value('name'),
                'نوع العقد'=>DB::table('contract_types')->where('id',$employee->contract_types_id )->value('name'),
                'تاريخ التعيين'=>$employee->hiring_date,
                'تاريخ  بدايه آخر عقد'=>$employee->contract_starting_date,
                'تاريخ نهايه آخر عقد'=>$employee->contract_ending_date,
                'تاريخ الالتحاق بالتأمين'=>$employee->socialinsurance_join_date,
                'المرتب الأساسي'=>$employee->basic_salary,
                'المرتب المتغير'=>$employee->variable_pay,
                'الوظيفة'=>DB::table('business_jobs')->where('id',$employee->job_id)->value('name'),
                'القسم'=>DB::table('business_departments')->where('id',DB::table('business_jobs')->where('id',$employee->job_id)->value('business_department_id'))->value('name'),
                'الاداره'=>DB::table('business_administrations')->where('id',DB::table('business_departments')->where('id',DB::table('business_jobs')->where('id',$employee->job_id)->value('business_department_id'))->value('business_administration_id'))->value('name'),
                'الفرع'=> DB::table('business_branches')->find($employee->branch_id)->name,
                'كود المدير المباشر'=>DB::table('employee_general_data')->where('id','=',$employee->manager_id)->value('code'),
                'اسم المدير المباشر'=>DB::table('employee_general_data')->where('id','=',$employee->manager_id)->value('employee_name'),
                'يعامل ضمن الحضور والأنصراف؟' =>($employee->attendable == 1 ? 'نعم' : 'لا'),
                'له اجازات سنويه؟' =>($employee->annual_vacation == 1 ? 'نعم' : 'لا'),
                'عدد الأيام خلال السنه'=>$employee->annual_vacation_days_per_year,
                'له مكافئه نهايه خدمه؟'=>($employee->end_service_reward == 1 ? 'نعم' : 'لا'),
                'عدد الأيام للسنه'=>$employee->end_service_reward_days_per_year,
                'خاضع للتامين الصحي ؟'=>($employee->employee_medical_insurance_statue == 1 ? 'نعم' : 'لا'),
                'نوع التأمين'=>$employee->medical_insurance_type,
                'اسم شركه التأمين'=>DB::table('medical_insurances')->where('id','=',$employee->medical_insurance_id)->value('name'),
                'رقم بوليصه التأمين'=>$employee->medical_insurance_number,
                'تاريخ بدايه التأمين'=>$employee->medical_insurance_start_data,
                'تاريخ نهايه التأمين'=>$employee->medical_insurance_end_data,
                'رقم الحساب البنكي'=>$employee->employee_account_number,
                'اسم صاحب الحساب البنكي'=>$employee->employee_bank_account_name,
                'البنك التابع له'=>DB::table('bank_data')->where('id','=',$employee->bank_id)->value('name'),
                'كود البنك'=>DB::table('bank_data')->where('id','=',$employee->bank_id)->value('code'),
            ];
        }
        return  $employee_array;
    }
}
